# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Afroz Ahamad
tagline:          
description:      'CS Undergrad @ BITS Pilani'
url:              http://enigmaeth.github.io/
baseurl:          /

author:
  name:           'Afroz'
  url:            https://twitter.com/enigmaeth

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/enigmaeth/enigmaeth.github.io
